name: Build .NET Framework 3.5 Console App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1

      - name: Replace %VERSION% with last commit hash
        run: |
          $filePath = "AutoBackupFiles/Program.cs"
          $content = Get-Content $filePath
          $updatedContent = $content -replace "%VERSION%", $(git rev-parse --short HEAD)
          Set-Content $filePath $updatedContent
        shell: pwsh

      - name: Restore NuGet packages
        run: nuget restore AutoBackupFiles.sln

      - name: Build solution
        run: msbuild AutoBackupFiles.sln /p:Configuration=Release

      - name: Archive build artifacts
        if: ${{ success() }}
        uses: actions/upload-artifact@v4
        with:
          name: Build-Output
          path: |
            **/bin/Release/*

      - name: Build MSI with Advanced Installer
        uses: caphyon/advinst-github-action@main
        with:
          aip-path: 'Auto Backup Files.aip'
          aip-build-name: 'DefaultBuild'
          aip-package-name: 'setup.msi'
          aip-output-dir: '${{ github.workspace }}\setup\setup.msi'
        
      - name: Archive MSI
        uses: actions/upload-artifact@v4
        with:
          name: MSI-Installer
          path: |
            setup.msi